### ISSUE TITLE
Error in the house

### ISSUE THREAD

**Issue by FleXoft** [godbout/alfred-kat#4]
[12:21:53.584] KAT[Script Filter] Queuing argument 't'
[12:21:53.677] KAT[Script Filter] Queuing argument 'te'
[12:21:53.846] KAT[Script Filter] Script with argv 'te' finished
[12:21:53.848] ERROR: KAT[Script Filter] Code 255: Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /Users/flex/Dropbox/Alfred/Alfred.alfre in /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
[12:21:53.849] ERROR: KAT[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /Users/flex/Dropbox/Alfred/Alfred.alfre in /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
[12:21:53.859] KAT[Script Filter] Queuing argument 'tes'
[12:21:53.951] KAT[Script Filter] Queuing argument 'test'
[12:21:54.122] KAT[Script Filter] Script with argv 'test' finished
[12:21:54.129] ERROR: KAT[Script Filter] Code 255: Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /Users/flex/Dropbox/Alfred/Alfred.alfre in /Users/flex/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8CC9273E-F1CF-42C5-A09C-64DD1D995FB3/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186

**Comment by godbout** [comment]
works fine here. you've got an SSL issue. lots of SSL have been revoked a few days ago by letsencrypt. what site you're pinging? check workflow env and let me know. i'm using kickasstorrents . to (without the spaces of course) and it works well.

**Comment by FleXoft** [comment]
It's Ok now.

**Comment by godbout** [comment]
you're welcome. you can make a donation of USD1,000,000 through the github sponsoring. thanks!
